project:
  type: website
  output-dir: docs

website:
  title: "Alex Leon's Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Leonalex0404/rcc_blog_real
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

